### ISSUE TITLE
Cache VerifyPermissions call

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/attach#133]
For instance, StorageService calls it for every single method.

**Comment by tiainen** [comment]
Is this an issue because the allow permission dialog is being presented to the user each time? In that case I would assume that when the user has granted permissions, the dialog would no longer show up when that same permission is verified later on?

**Comment by jperedadnr** [comment]
No, by default, the dialog shows once, if user accepts it. If permission is denied, it shows again with the option "don't show again". 
It is not a big issue, it just prevents the whole native chain of calls between the different layers, so I'd say it will have a little bit of performance gain.
