### ISSUE TITLE
Published poms don't include dependencies

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/attach#158]
The pom files that are generated by the gradle maven publish don't have the project dependencies as defined in their respective build.gradle configuration. This requires a project that uses an attach service to have to explicitly define the util dependency as well. Including the required dependencies frees the developer from having to do that by letting the maven dependency management handle it.

**Comment by tiainen** [comment]
I believe we can also remove any JavaFX dependencies entirely from the list of dependencies. A project that uses an attach service will almost always have a dependency on JavaFX already defined.

**Comment by jperedadnr** [comment]
Yes, so far we use `javafx.graphics` in most of the Attach services, and that is usually included in any JavaFX project.
