### ISSUE TITLE
Update JavaDoc

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/attach#208]

**Comment by AlmasB** [comment]
Any specific javadoc?

**Comment by jperedadnr** [comment]
A temporary link for Attach Javadoc is https://docs.gluonhq.com/attach/javadoc/4.0.9/

It would be good if we could review it, making sure:
- there is no reference to Charm Down anymore
- each service provides one or more example (and it is updated)
- we favour now each service `create()` method over `Services.get(service)`
- for Android, there is no need to modify the AndroidManifest, the Client plugin takes care of it. But this is of course if the plugin is used. This should be mentioned in the javadoc.

**Comment by AlmasB** [comment]
I'll be reviewing it from time to time, updating this thread and javadoc in the sources as necessary:

- [x] there is no reference to Charm Down anymore
- [x] each service provides one or more example (and it is updated)
- [x] we favour now each service create() method over Services.get(service) 
- [x] for Android, there is no need to modify the AndroidManifest, the Client plugin takes care of it. But this is of course if the plugin is used. This should be mentioned in the javadoc.

**Comment by AlmasB** [comment]
@jperedadnr Potential Charm Down stuff:

- DesktopDisplayService.java: 58

```
    @Override
    public boolean isTablet() {
        return "tablet".equals(System.getProperty("charm-desktop-form"));
    }
```

- BleService.java: 177

```
<activity android:name="com.gluonhq.impl.charm.down.plugins.android.PermissionRequestActivity" />
```

- DisplayService.java : 108

```
    /**
     * Returns true if the device is considered a tablet.
     * @return True if the device is considered a tablet.
     *
     * Running on Desktop, if the property {@code charm-desktop-form}
     * is set to {@code tablet}, it will return true. False otherwise
     */
    boolean isTablet();
```

- ShareService.java: 47

```
 * When sharing files, the Attach
 * <a href="http://docs.gluonhq.com/charm/javadoc/latest/com/gluonhq/charm/down/plugins/StorageService.html">
 * StorageService</a> can be used to create/read the file.
```

If you provide guidance on how to fix these, happy to do so.

**Comment by jperedadnr** [comment]
- `charm-desktop-form` is okay, we use Charm for Gluon Mobile. Doesn't have `"down"`
- `<activity android:name="com.gluonhq.helloandroid.PermissionRequestActivity" />`
-  `<a href="http://docs.gluonhq.com/attach/javadoc/latest/com.gluonhq.attach.storage/com/gluonhq/attach/storage/StorageService.html">` (current [link](https://docs.gluonhq.com/attach/javadoc/4.0.9/com.gluonhq.attach.storage/com/gluonhq/attach/storage/StorageService.html)).

**Comment by AlmasB** [comment]
Can you give an example for number 4 and how to fix it?

> for Android, there is no need to modify the AndroidManifest, the Client plugin takes care of it. But this is of course if the plugin is used. This should be mentioned in the javadoc.

**Comment by jperedadnr** [comment]
If you check for instance the [Android configuration](https://github.com/gluonhq/attach/blob/master/modules/share/src/main/java/com/gluonhq/attach/share/ShareService.java#L68) for `Share` service, both the file and the AndroidManifest modifications are done by the Client plugin ([file](https://github.com/gluonhq/attach/blob/master/modules/share/src/main/resources/META-INF/substrate/dalvik/res/xml/file_provider_paths.xml) and [manifest](https://github.com/gluonhq/attach/blob/master/modules/share/src/main/resources/META-INF/substrate/dalvik/AndroidManifest.xml))
so the developer doesn't need to do anything.

You can easily verify that creating a [Start](https://start.gluon.io) project with the Share service included, and building for Android.

We are developing some Attach documentation that explains this in detail. Nonetheless, the javadoc in Attach has to mention what is needed (like we do now) and what the Client plugin will be doing for the developer.

**Comment by AlmasB** [comment]
So what needs to be done is: 

- add a note to Android configuration (if present) that if the Client plugin is used then the modifications are not necessary

**Comment by jperedadnr** [comment]
Yes. Add this link `https://docs.gluonhq.com/client` to `Client plugin`. I'd say that the plugin takes care of the modifications (not that these are not necessary).
