### ISSUE TITLE
No fine (GPS) position on Android anymore

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/attach#222]
For some time now I don't get the PositionService working anymore, so that it would provide me with periodic position updates from GPS. When I start the service I get one position and that's it. Also the GPS symbol, which normally appears in the status bar for any app which activates GPS, does not show up anymore. I have provided a slightly modified HelloGluon version which should show the issue. This behaviour is consistent on all my devices and I even made sure that they had a valid GPS fix before I started the test. I even provided my own AndroidManifest.xml file (is that actually still necessary?) requesting coarse and fine location, but it did not change anything. So what is going on here? I tested this with client-maven-plugin 0.1.33 as well as 0.1.34-SNAPSHOT and Attach 4.0.9 as well as 4.0.10-SNAPSHOT on my Samsung tablet (Android 10) and phone (Android 8).
[HelloGluon.zip](https://github.com/gluonhq/attach/files/5453502/HelloGluon.zip)

**Comment by jperedadnr** [comment]
Can you add to your main `System.setProperty(Constants.ATTACH_DEBUG, "true");` and try again? See the console for possible indications.

**Comment by mipastgt** [comment]
I did what you asked me to do. In addition I also modified the example a bit so that the PositionService can be activated/deactivated on a button press. (I have the feeling that this makes a difference too.) The state is now that I can get GPS position updates in 1 second intervals on my Samsung phone (Android 8) but for exactly the same APK file this still does not work on my Samsung tablet (Android 10). It looks as if there are some strange permission problems. If you look at the output you can see that on the tablet there are 3 location providers available but although I request the highest precision the network is returned as the best location provider which is of course nonsense. On the phone gps is returned instead.

```
11-13 18:18:52.498  6969  7598 V GluonAttach: DalvikPositionService, start called
11-13 18:18:52.502  6969  7598 V GluonAttach: Available location providers on this device: [passive, gps, network].
11-13 18:18:52.502  3400  4040 D LocationManagerService: get providerss: [], enabledOnly = false
11-13 18:18:52.502  3400  4040 D LocationManagerService: get providerss: [network], enabledOnly = false
11-13 18:18:52.503  6969  7598 V GluonAttach: Picked network as best location provider.
11-13 18:18:52.506  6969  7598 V GluonAttach: Last known location for provider network: 1605283071448 / 48,738739 / 9,179853 / 0,000000
11-13 18:18:52.506  6969  7598 V GluonAttach: [DALVIKPOSITION] update to 1605283071448, 48.73873873873874, 9.179852991735839, NaN
11-13 18:18:52.506  6969  7598 D GluonAttach: Native layer got new position: 1605283071448, 48.738739, 9.179853, nan
11-13 18:18:52.506  6969  7598 D GraalGluon: ATTACH_GRAAL, tid = 7598, existed? 1, graalEnv at 0x7ce6afa2c0
11-13 18:18:52.506  6969  7598 D GraalGluon: DETACH_GRAAL, tid = 7598, graalVM = 0x7c84d83200, existed = 1, env at 0x7ce6afa2c0
11-13 18:18:52.507  6969  7598 V GluonAttach: Creating LooperTask to request location updates every 0 milliseconds or 0,000000 meters.
11-13 18:18:52.508  6969  7598 D GraalGluon: DETACH_DALVIK, tid = 7598, existed = 1, env at 0x7ce6a1c840
11-13 18:18:52.510  3400  4040 D LocationManagerService: request de6737d fused Request[ACCURACY_BLOCK fused requested=+10m0s0ms fastest=+10m0s0ms] from com.gluonhq.samples.hellogluon(10308 foreground)
11-13 18:18:52.510  3400  4040 D LocationManagerService: provider request: fused ProviderRequest[ON interval=+10m0s0ms]
```
[HelloGluon2.zip](https://github.com/gluonhq/attach/files/5538438/HelloGluon2.zip)

**Comment by jperedadnr** [comment]
Have you tried outside, in an open space? I had times when it was working fine at home, but for some reason at some point it also switched to network, and I had to get outside.

**Comment by mipastgt** [comment]
I tried it outside on my balcony as well as inside. The different behaviour between the two devices is very consistent. So far I have not observed any switches in the behaviour.

**Comment by mipastgt** [comment]
I just did an additional test. I went out on my balcony and explicitly switched off WLAN, so that the tablet did not have any network (also no LTE or such) but even this does not make a difference. GPS still doesn't work.

**Comment by jperedadnr** [comment]
Can you check the app permissions on your phone (via app info)? 
Sometimes, for some reasons, there is no dialog asking to enable the permission and this gets denied by default. Check that you allow GPS. 

Your app works fine for me on my Pixel XL (Android 10), even if I'm at home (close to a window):

```
[Fri Nov 13 19:32:11 CET 2020][INFO] [SUB] V/GluonAttach(17973): Available location providers on this device: [passive, gps, network].
[Fri Nov 13 19:32:11 CET 2020][INFO] [SUB] V/GluonAttach(17973): Picked gps as best location provider.
[Fri Nov 13 19:32:11 CET 2020][INFO] [SUB] V/GluonAttach(17973): Creating LooperTask to request location updates every 0 milliseconds or 0,000000 meters.
[Fri Nov 13 19:32:11 CET 2020][INFO] [SUB] D/GraalGluon(17973): DETACH_DALVIK, tid = 18040, existed = 1, env at 0x71fb771f00
[Fri Nov 13 19:32:13 CET 2020][INFO] [SUB] V/GluonAttach(17973): Android location changed: XX,611622 / -XX,785152 / 739,299988
[Fri Nov 13 19:32:13 CET 2020][INFO] [SUB] V/GluonAttach(17973): [DALVIKPOSITION] update to XX.6116224, -XX.7851522, 739.2999877929688
```

(with Client 0.1.34, Attach 4.0.9)
App info shows permissions enabled for storage and location (only when app is in use).

**Comment by mipastgt** [comment]
Android 8 (my phone) only distinguishes between Position (off/on) and it is on.
Andorid 10 (my tablet) distinguishes between Position (off/only when app is in use/always) and it is set to "only when app is in use".

**Comment by jperedadnr** [comment]
It is obvious that you would have tested Google Maps on your tablet, or other GPS apps... and GPS works just fine, right?

**Comment by mipastgt** [comment]
Of course :-) I ran GPSTest and other apps just fine.

**Comment by jperedadnr** [comment]
Sure, I had to ask ;)

Did PositionService ever work before on your tablet?

**Comment by mipastgt** [comment]
Yes, it always worked until some time ago. The problem is I cannot say exactly when it stopped working. I haven't used it for several months because I was working on other stuff.

**Comment by mipastgt** [comment]
I would also like to give it a try with the official 4.0.10 build of Attach as soon as it becomes available on Maven Central. Currently, there seems to be something wrong with the build on GitHub.

**Comment by jperedadnr** [comment]
Yes, we are aware. We switched recently from Travis to GA, and the release workflow is failing...

**Comment by mipastgt** [comment]
I investigated this issue a little bit further. I modified the DalvikPositionService
so that it explicitly requests a "gps" location provider if gpsEnabled in the constructor
is true. The result is that I get the following exception when I later stop the service
again. (The delay of the exception is probably caused by the fact that the looperTask
does not do any exception handling.)

```
11-21 16:08:00.715 30811 32285 D GluonAttach: Stop listening for location changes
11-21 16:08:00.715 30811 32285 D GraalGluon: ATTACH_DALVIK, tid = 32285, existed? 1, dalvikEnv at 0x7d79d7b100
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethod called with pending exception java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at java.lang.Exception android.os.Parcel.createException(int, java.lang.String) (Parcel.java:2088)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at void android.os.Parcel.readException(int, java.lang.String) (Parcel.java:2056)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at void android.os.Parcel.readException() (Parcel.java:2004)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at android.location.Location android.location.ILocationManager$Stub$Proxy.getLastLocation(android.location.LocationRequest, java.lang.String) (ILocationManager.java:1374)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at android.location.Location android.location.LocationManager.getLastKnownLocation(java.lang.String) (LocationManager.java:1433)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at void com.gluonhq.helloandroid.DalvikPositionService.initialize() (DalvikPositionService.java:186)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]   at void com.gluonhq.helloandroid.DalvikPositionService.start(long, float, boolean) (DalvikPositionService.java:104)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] Caused by: android.os.RemoteException: Remote stack trace:
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 	at com.android.server.LocationManagerService.checkResolutionLevelIsSufficientForProviderUseLocked(LocationManagerService.java:2299)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 	at com.android.server.LocationManagerService.getLastLocation(LocationManagerService.java:3080)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:594)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 	at android.os.Binder.execTransactInternal(Binder.java:1056)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 	at android.os.Binder.execTransact(Binder.java:1029)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] (Throwable with no stack trace)
11-21 16:08:00.715 30811 32285 F ples.hellogluo: java_vm_ext.cc:570] 
11-21 16:08:00.716 30811 32285 F ples.hellogluo: java_vm_ext.cc:570]     in call to CallVoidMethod
```

This is strange because in the actually used manifest the requested permission is granted.
I verified this with the apkanalyzer like this:

```
$ JAVA_HOME=$JAVA8_HOME ~/Library/Android/sdk/tools/bin/apkanalyzer manifest print HelloGluon-3.apk 
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="1"
    android:versionName="1.0"
    android:compileSdkVersion="29"
    android:compileSdkVersionCodename="10"
    package="com.gluonhq.samples.hellogluon"
    platformBuildVersionCode="29"
    platformBuildVersionName="10">

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="29" />

    <supports-screens
        android:xlargeScreens="true" />

    <uses-permission
        android:name="android.permission.INTERNET" />

    <uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application
        android:label="HelloGluon"
        android:icon="@ref/0x7f080000"
        android:debuggable="true"
        android:appComponentFactory="android.support.v4.app.CoreComponentFactory">

        <activity
            android:name="com.gluonhq.helloandroid.MainActivity"
            android:configChanges="0xa0">

            <intent-filter>

                <category
                    android:name="android.intent.category.LAUNCHER" />

                <action
                    android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.gluonhq.helloandroid.PermissionRequestActivity" />
    </application>
</manifest>
```

Also in the dialogue, which pops up when I launch the app for the first time, I grant
the permission.

So there seems to be something wrong with the permission handling but I have no idea what.

**Comment by jperedadnr** [comment]
Ok, good that you are making progress.
There is a related thread here: https://stackoverflow.com/questions/32083913/android-gps-requires-access-fine-location-error-even-though-my-manifest-file

Looks indeed like something is missing from how we handle permissions.  Hard to check without being able to reproduce the issue. Maybe you can try to find out? Note that the `PermissionRequestActivity` is here: https://github.com/gluonhq/substrate/blob/master/src/main/resources/native/android/android_project/app/src/main/java/com/gluonhq/helloandroid/PermissionRequestActivity.java, and that is called from `DalvikPositionService` constructor. 

Not sure if when `start` is called, we should do another check of those permissions?

**Comment by mipastgt** [comment]
Update: I have now written a native Android app which behaves similarly to the example I have provided here. It works correctly on all my devices. As soon as I click the button to start the position updates the GPS symbol shows up in the status bar and disappears when I hit the button again. I also get the expected location updates. So my devices are ok. I will now try to compare that to the Attach code to see were it goes wrong there.

**Comment by mipastgt** [comment]
I spent the sunday further investigating this issue and have finally found the problem. With the above pull request applied I can access GPS again. I wonder though why not all devices with Android 10+ are affected by this bug.

**Comment by jperedadnr** [comment]
Good finding!

**Comment by mipastgt** [comment]
Did you receive my [CLA](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY) so that this can be integrated? I did not get any feedback on that.

**Comment by jperedadnr** [comment]
Yes, thanks, I've added a label to your PR.
