### ISSUE TITLE
Set Application Icon Badge Number

### ISSUE THREAD

**Issue by javasuns** [gluonhq/attach#247]
Need implementation for setting app icon badge number
![image](https://user-images.githubusercontent.com/13131668/109681262-f7037d80-7b85-11eb-83e7-1bf6514a3390.png)

**Comment by websystemtechnology** [comment]
Hi i look the code https://github.com/gluonhq/attach/pull/248/checks#issue-comment-box: you coup merge this into master branch?
thank you
