### ISSUE TITLE
debugAttach fails on Android with new clang versions

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/attach#250]
On Android, `util.h` defines `boolean debugAttach;`, and that header is added to all services.
When linking those services, this exception is thrown:
```
[INFO] ==================== LINK TASK ====================
[INFO] [SUB] ~/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: error: /Sample/target/client/aarch64-android/gvm/lib/libutil.a(util.o): multiple definition of 'debugAttach'
[INFO] [SUB] /~/.gluon/substrate/Android/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld.gold: /Sample/target/client/aarch64-android/gvm/lib/libaccelerometer.a(accelerometer.o): previous definition here
```

This happens with clang 11.0.5, but not with older versions (9.0.8)

We need to move the constant `debugAttach` to a function `isDebugAttach()`.

**Comment by AlmasB** [comment]
So a fix for this is to replace all occurrences of `debugAttach` with `isDebugAttach()`, which in turn returns a private variable named `debugAttach`?

**Comment by jperedadnr** [comment]
I'm on it already.

**Comment by jperedadnr** [comment]
You can review https://github.com/gluonhq/attach/pull/251 if you have the time. Build it on Linux and then try a sample on Android with or without `System.setProperty(Constants.ATTACH_DEBUG, "true");`
