### ISSUE TITLE
[Storage] Add support to work with android 10+

### ISSUE THREAD

**Issue by rnayabed** [gluonhq/attach#263]
When using Gluon Storage, one can get the PublicDirectory and use it as a path, but when you try to use it (Create file) using java file api, it fails. You need to add `android:requestLegacyExternalStorage="true"` to the manifest to make it work, but it is ignored from android 11

**Comment by rnayabed** [comment]
PublicStorage doesnt work, but PrivateStorage works

**Comment by bubbleguuum** [comment]
`android:requestLegacyExternalStorage="true"` is ignored on Android 11+ only if using `targetSdkVersion 30` (which will be mandatory this fall for app updates to the Google Play Store)

**Comment by rnayabed** [comment]
@jperedadnr this will not work in android 11+ because that flag is comment ignored from 11 onwards

**Comment by jperedadnr** [comment]
@rnayabed Thanks, yes, I'm aware this should work for all devices with Android 10 or lower, and it will be useless, but harmless for Android 11+.

For Android 11+ (I can't test so far), there is this MANAGE_EXTERNAL_STORAGE new permission, and I'm giving it a try. It works on my Android 10, could you test on 11?

**Comment by rnayabed** [comment]
Unfortunately I don't have an android 11 device but I can try and ask our community. Some of them seem to have android 11 devices.

Thanks for the very fast reply. 

I think android brings some sort of "scoped storage" with android 10 that I'm not very familiar with. Its probably the reason why it's behaving like this

**Comment by bubbleguuum** [comment]
`MANAGE_EXTERNAL_STORAGE` cannot be used as a general solution, as for publishing on the Play Store it requires approval from Google, and the allowed use cases are very narrow. See:

https://developer.android.com/training/data-storage/manage-all-files

For proper access to storage on Android 11+, there is no other way than via Scoped Storage, with the annoyances, complexity and limitations that go with it... Developers have been complaining about it for the last 2 years.

**Comment by jperedadnr** [comment]
@bubbleguuum so in your opinion you wouldn't implement MANAGE_EXTERNAL_STORAGE, but directly the API with ACTION_CREATE_DOCUMENT, ACTION_OPEN_DOCUMENT, ...? The docs don't say that Google Play will reject such permission by default, if you have a good use case, such as file management, it will be allowed...

**Comment by bubbleguuum** [comment]
Google will never give your app MANAGE_EXTERNAL_STORAGE unless your app is exactly one of use case described. 
And even if it is, good luck obtaining it. I'd really stay away from it unless your app really needs it and one of the use cases listed.
Most apps do not need it.

Apps can still access storage using ACTION_CREATE_DOCUMENT, ACTION_OPEN_DOCUMENT, ACTION_OPEN_DOCUMENT_TREE. The latter is for accessing a folder (reading/writing files and folderss) and all its subfolders. The root of storage, the Downloads folder and Android/data/* are excluded. The Media Store, File, Downloads collections can also be used for relevant files. All this stuff is totally Android specific and cannot really be abstracted.
