### ISSUE TITLE
How can I make custom plugin with Gluon Client Plugin, however with old javafxmobile-plugin is too easy process?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/attach#264]
With javafxmobile-plugin it was too easy to make custom native codding for Android, Desktop & ISO. But now I think it's too complex to make even a very simple native codding.
Actually I want use some Android native codding, but I think, I have to use C language too for very simple task.
Javafxmobile-plugin was allowed to use native Android codding in Android/src folder & it was too easy & simple method.
e.g. See how easy is to add native codding [here](https://docs.gluonhq.com/samples/gonative/).

Is there is some easy way to implement native codding especially for Android using java only codding. Or where can someone starts to implement native codding using new Gluon Client Plugin.

I think, understanding & working on attach project for own custom codding is too complex process for newbee.

I have couple of custom plugins for Android / Desktop in javafxmboile-plugin & I want to convert all of them in Client plugins, but am unable to continue. Any helps is very appreciated.

**Comment by jperedadnr** [comment]
Indeed, doing services now for Android is more complex than before. The main reason (that explains why c code is required) is that now we have two different VMs (GraalVM/Java and Android/Java) while before all was one single VM (Android/Java).

I've created this experimental repository: https://github.com/jperedadnr/Custom-Attach
It has a dummy `LogService` to show how a custom service can be created for desktop, iOS and Android.

**Comment by ctoabidmaqbool** [comment]
@jperedadnr Thanks for posting a sample project and helps.
Actually I have converted my many custom old charmdown plugins to attach just now. Firstly I takes me about two weeks to understand Attach plugins how it work, even to make a very simple hello world plugin. But now it's not much problem to make a new one.

I think there should be some step-by-step docs to make a new helloworld plugin e.g. here https://docs.gluonhq.com/attach/, also update it to current version. For new dev it's very difficult where to start if some feature is missing in Attach. I will try to make public repository of my custom attach plugins and there sample projects.

**Comment by jperedadnr** [comment]
The official repository with a dummy LogService is https://github.com/gluonhq/AttachExtended
The documentation for Attach includes some details for advanced users: https://docs.gluonhq.com/#_building_attach
In any case your contributions (as a custom service or as a PR to Attach) are very welcome.
