### ISSUE TITLE
It is unclear how the "current" platform is selected

### ISSUE THREAD

**Issue by johanvos** [gluonhq/attach#272]
Often, when running JavaFX samples with Attach on desktop, one gets this message:
 INFO: javafx.platform is not defined. Desktop will be assumed by default.

It is not clear that this comes from Attach.
Also, the JavaDoc needs to mention that if the `javafx.platform` property is not specified, the value of the "platform" will be set to DESKTOP.

**Comment by jperedadnr** [comment]
Fixed with #273
