### ISSUE TITLE
PushNotification on Android overwrites the last notification popup on the device

### ISSUE THREAD

**Issue by cseeberg** [gluonhq/attach#288]
It seems that the Android implementation uses a hardcoded value (REQUEST_CODE) that will cause all incoming push-notifications to be treated as the same request, thus overwriting the previous notification popup.  The expected behavior would be to see a list of the push-notifications popups on the device.

I would think that the following code PushFcmMessagingService:145:
`notificationManager.notify(REQUEST_CODE,  getNotification(title, body,  id.isEmpty() ? UUID.randomUUID().toString() : id));`

could be replaced with:
`int uniqueRequestNumber = (int) (System.currentTimeMillis() %  Integer.MAX_VALUE);`
`notificationManager.notify(uniqueRequestNumber, 
          getNotification(uniqueRequestNumber, title, body,  id.isEmpty() ? UUID.randomUUID().toString() : id));
`

The above method to get a uniqueRequestNumber is crude but efficient., and can be replaced.

Finally, the _uniqueRequestNumber_ should be used by the PushFcmMessagingService:158 _getNotification_ method like:

` PendingIntent resultPendingIntent = PendingIntent.getActivity(application, uniqueRequestNumber, 
                resultIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_ONE_SHOT);`

**Comment by jperedadnr** [comment]
Fixed with #289
