### ISSUE TITLE
iOS Barcodescan Service sends 'nil' results

### ISSUE THREAD

**Issue by molbertz** [gluonhq/attach#306]
I have some iPads where the scan window simply closes and returns an empty value.

I've looked at the code and I've noticed that **BarcodeScan.m** sometimes sends 'nil' results to the **IOSBarcodeScanService.java** mid scan. This leads me to believe the call `public Optional<String> scan(String title, String legend, String resultText)` returns prematurely. 
That seems to be some kind of race condition, though. Because apparently the scan window only closes once a valid value is detected. And yet the service call returns with _nothing_.

The logs support my theory as they show multiple `AttachLog(@"String: none");` **but** also lots of valid results via `AttachLog(@"String: %@", detectionString);`.

If I understand correctly once a call to: `sendScanResult()` is made, the service call (IOSBarcodeScanService.java) returns the given value to the user's code. So why would the code in `BarcodeScan.m` essentially end the service call if **one** `AVMetadataObject` contains no valid string result?
The other objects in the `metadataObjects` array might contain valid results. Also, as far as I know the entire `captureOutput` method gets called multiple times by the OS. So many more chances for valid results.

**Conclusion:**
I suggest simply removing the lines 283 and 284 in `BarcodeScan.m` as they seem to cause problems on some devices. Also, I don't see the value in sending an empty result mid scan.
I tested this already by building the service myself and it now works on all my devices.

So. Have I made some mistakes in my research? Are the lines 283 and 284 there for a reason?

**Comment by jperedadnr** [comment]
Thanks for your report. Your conclusion seems accurate.

Which iOS versions or iPhone/iPad devices are you using?

**Comment by molbertz** [comment]
Hi,

Thanks for reviewing my findings. So the issue occurred over a number of devices with different iOS versions. So, I'm not sure how helpful this info will be. The issue happened using:

- iPhone 13 (customer complaint)

- iPad Air 4th Generation (development device) iOS 15.5

- iPhone 12 Pro (development device) iOS 15


The following device however did not show the issue at all:

- iPad 6th Generation (development device) iOS 15.5

**Comment by jperedadnr** [comment]
Thanks, that is helpful. We have already merged a possible fix with your suggestion, so if you are able to test again with the 4.0.15-SNAPSHOT, that would be great.
Just add this plugin repository to your pom:
```
    <pluginRepositories>
        <pluginRepository>
            <id>Snapshots</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by molbertz** [comment]
Thanks. I'll give this a try. I can't exactly say when I'll get to it, though. I hope to fit this into my schedule for the next couple of days.

**Comment by molbertz** [comment]
I didn't have the time to check the snapshot yet. But I looked at the merge request. It's quite literally the same thing I changed when I compiled the service locally. So, I guess unless other things changed it should be alright.
