### ISSUE TITLE
PictureService: Camera doesn't show up on iPhone 13

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/attach#326]
Follow-up of #322

**Comment by jperedadnr** [comment]
@molbertz As a follow-up, I've created a PR for this issue: #327, in the very same way we did for the barcode service.

If you have the time, it would be great if you could test it/review it. Thanks!

**Comment by molbertz** [comment]
Just looked at the changes. Seems a bit more complex than the barcode-scan. I can just check out the branch from your personal repo, yes?

**Comment by jperedadnr** [comment]
Sure, you can either create a patch from my commit and apply it to your repo, or simply clone my branch, indeed.

**Comment by molbertz** [comment]
I cloned your repo and compiled barcode-scan and pictures. I'm using the HelloGluon sample to test. So far so good. Unfortunately I just lost the VPN to our macOS machine. I don't know how long that is going to take.

Anyway, I noticed something I missed with the JavaDoc for `BarcodeScanService.java`.

```
 * <pre>
 * {@code BarcodeScanService.create().ifPresent(service -> {
 *      service.resultProperty().addListener((obs, ov, nv) ->
 *          System.out.printf("Scanned result: %s", nv.getResult()));
 *      barcodeScanService.asyncScan();
 *  });}</pre>
```

`barcodeScanService.asyncScan()` should be `service.asyncScan()`

**Comment by jperedadnr** [comment]
Okay, no problem.
Good catch, I've just fixed it.

**Comment by molbertz** [comment]
Taking a picture works on iPhone 13 Pro. Selecting a picture also works.

EDIT: I didn't try the ShareService line from the example though.

**Comment by jperedadnr** [comment]
Cool, thanks for testing!
Share service should work, it is not affected by the nested event lock.

**Comment by molbertz** [comment]
No problem. Is there already a release planned for 4.0.16 btw?

**Comment by jperedadnr** [comment]
You can review the PR if you want (even just approve it and comment that you tested it on iPhone 13).
We'll do a release with these changes soon.

**Comment by molbertz** [comment]
Okay, I'll have a look at that.
